import { chromium } from 'playwright-core'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', headless: true })
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } })
page.on('pageerror', (e) => console.log('EXCEPTION:', e.message))
const errors = []
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(800)
if ((await page.locator('.gate-card').count()) !== 1) errors.push('login não apareceu')
await page.screenshot({ path: process.env.OUT + '/B1-login.png' })
await page.fill('input[autocomplete="username"]', 'fortunato')
await page.fill('input[type="password"]', 'errada')
await page.click('text=Entrar')
await page.waitForTimeout(500)
if ((await page.locator('.gate-error').count()) !== 1) errors.push('erro de senha não apareceu')
await page.fill('input[type="password"]', 'fortunato2026')
await page.click('text=Entrar')
await page.waitForSelector('.sl-root', { timeout: 10000 }).catch(() => errors.push('não entrou com a senha certa'))
await page.reload({ waitUntil: 'networkidle' })
await page.waitForSelector('.sl-root', { timeout: 10000 }).catch(() => errors.push('sessão não persistiu'))
await page.click('text=Sair')
await page.waitForTimeout(800)
if ((await page.locator('.gate-card').count()) !== 1) errors.push('sair não voltou pro login')
await page.goto('http://localhost:4173/#gerar-acesso', { waitUntil: 'networkidle' })
await page.waitForTimeout(500)
await page.fill('.gate-card input >> nth=0', 'clientinho')
await page.fill('.gate-card input >> nth=1', 'senha123')
await page.click('text=Gerar')
await page.waitForTimeout(400)
const linha = await page.locator('.gate-output').inputValue()
console.log('linha gerada:', linha.slice(0, 60) + '...')
if (!linha.includes('"usuario":"clientinho"')) errors.push('gerador falhou')
await browser.close()
if (errors.length) { console.log('PROBLEMAS:', errors.join(' | ')); process.exit(1) }
console.log('QA LOGIN OK')
